language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
env:
  global:
    - MAKEFLAGS="-j 2"
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build --no-default-features &&
  travis-cargo test --no-default-features
cache:
  pip: true
  cargo: true
