[package]
name = "pbrt"
version = "0.2.7"
authors = ["Jan Walter <jan@janwalter.com>"]

[features]
default = ["openexr"]

[dependencies]

crossbeam = "0.3"
getopts="0.2.15"
half="1"
image="0.18"
num="*"
num_cpus = "1.2"
openexr = { version = "0.5", optional = true }
pbr = "1.0"
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
ply-rs = "0.1.1"
time = "0.1"
typed-arena = "1.3.0"
