[package]
name = "pbrt"
version = "0.2.3"
authors = ["Jan Walter <jan@janwalter.com>"]

[dependencies]

num="*"
num_cpus = "1.2"
image="0.17"
crossbeam = "0.3"
getopts="0.2"
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
pbr = "1.0"
typed-arena = "1.3.0"
time = "0.1.38"
