[package]
name = "pbrt"
version = "0.2.3"
authors = ["Jan Walter <jan@janwalter.com>"]

[dependencies]

crossbeam = "0.3"
getopts="0.2.15"
half="1"
image="0.17"
num="*"
num_cpus = "1.2"
openexr = "0.5"
pbr = "1.0"
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
time = "0.1"
typed-arena = "1.3.0"

[patch.crates-io]
openexr = { path = "../openexr-rs" }
