[package]
name = "pbrt"
version = "0.2.2"
authors = ["Jan Walter <jan@janwalter.com>"]

[dependencies]

num="*"
num_cpus = "1.0"
image="0.15.0"
crossbeam = "0.3"
getopts="0.2"
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
pbr = "1.0"
cpuprofiler = "0.0.3"
